### ISSUE TITLE
Note to self: Never attempt to reap a Wandering Trader 

### ISSUE THREAD

**Issue by DatrixTHLK2024** [JamCoreModding/reaping#5]
Hi there, I like the mod, but it crashed on me when reaping a wandering trader. 

Minecraft: 1.20.4
Fabric Mod Loader: 0.15.7
Fabric API: 0.96.11
Cloth Config: 13.0.121
Reaping: 3.0.1

Crash Log: https://gist.github.com/DatrixTHLK2024/fab72b9483b58714629a61c49c80fe17

**Comment by Jamalam360** [comment]
Looks like you need to install pehkui. I'll keep this issue open because Pehkui isn't supposed to be a required dependency
