### ISSUE TITLE
Crash on Forge

### ISSUE THREAD

**Issue by Valexfor12** [JamCoreModding/reaping#6]
Hello, I have 2 issues:

The first (and kind of most important one) is that whenever the Scythe pillager spawns the game crashes:

The game crashed whilst exception ticking world
Error: java.lang.IllegalArgumentException: class io.github.jamalam360.reaping.pillager.ReapingPillager is not an instance of interface net.minecraftforge.entity.IEntityAdditionalSpawnData;

Second: when i try to harvest mobs.
I've only used the iron Scythe so far but sometimes mob just insta die instead of becoming younger. I've still not understood the pattern, since it seems pretty random (up to now chicke ALWAY die, pigs have yet to die, cows are about 50/50, still need t try on other mobs) 
I play on forge, 1.20.4. Do you need any info (like other mods I have installed, etc)?

**Comment by Jamalam360** [comment]
For the second issue, there is a chance that entities die when you reap them. The chance lowers with the sharpness enchantment level, and with having a higher tier reaper (better material: diamond has less chance of death than iron etc.)

I'll look into the crash later on
